version: '3.4'

services:
  5createreactapp:
    image: 5createreactapp
    build:
      context: reactjs/5-createreactapp
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
